# $Id: Makefile.kmk 31634 2010-08-13 11:17:20Z noreply@oracle.com $
## @file
# Sub-Makefile for the Windows guest shared folder redirectory.
#

#
# Copyright (C) 2006-2007 Oracle Corporation
#
# Oracle Corporation confidential
# All rights reserved
#

SUB_DEPTH = ../../../../../..
include	$(KBUILD_PATH)/subheader.kmk

# Include sub-makefiles.
include $(PATH_SUB_CURRENT)/dll/Makefile.kmk
include $(PATH_SUB_CURRENT)/sys/Makefile.kmk

include	$(KBUILD_PATH)/subfooter.kmk

