/* Copyright (c) 2011 The WebM project authors. All Rights Reserved. */
/*  */
/* Use of this source code is governed by a BSD-style license */
/* that can be found in the LICENSE file in the root of the source */
/* tree. An additional intellectual property rights grant can be found */
/* in the file PATENTS.  All contributing project authors may */
/* be found in the AUTHORS file in the root of the source tree. */
/* This file automatically generated by configure. Do not edit! */
#ifndef VPX_CONFIG_H
#define VPX_CONFIG_H
#define RESTRICT

#ifdef RT_OS_WINDOWS
# define INLINE      __forceinline
#else
# define INLINE
#endif

/* Note: The rest of the preprocessor / constant stuff is done in Makefile.kmk. */

#endif /* VPX_CONFIG_H */