# $Id: Makefile.kmk 112403 2026-01-11 19:29:08Z knut.osmundsen@oracle.com $
## @file
# Sub-Makefile for the Storage library.
#

#
# Copyright (C) 2006-2026 Oracle and/or its affiliates.
#
# This file is part of VirtualBox base platform packages, as
# available from https://www.virtualbox.org.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, in version 3 of the
# License.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses>.
#
# SPDX-License-Identifier: GPL-3.0-only
#

SUB_DEPTH = ../../..
include $(KBUILD_PATH)/subheader.kmk

VBOX_PATH_STORAGE_SRC := $(PATH_SUB_CURRENT)

if !defined(VBOX_ONLY_EXTPACKS)
 include $(PATH_SUB_CURRENT)/testcase/Makefile.kmk

 #
 # StorageLib - The storage Library.
 #
 LIBRARIES += StorageLib #StorageLibNoDB

 StorageLib_TEMPLATE = VBoxR3Dll
 StorageLib_DEFS     = IN_VBOXDDU
 ifeq ($(USER),bird)
  StorageLib_DEFS.debug += RTMEM_WRAP_TO_EF_APIS
 endif

 StorageLib_SOURCES  = \
 	VD.cpp \
 	VDPlugin.cpp \
 	VDVfs.cpp \
 	VDIfVfs.cpp \
 	VDIfVfs2.cpp \
 	VDIfTcpNet.cpp \
 	VDI.cpp \
 	VMDK.cpp \
 	VHD.cpp \
 	DMG.cpp \
 	Parallels.cpp \
 	ISCSI.cpp \
 	RAW.cpp \
 	QED.cpp \
 	QCOW.cpp \
 	VHDX.cpp \
 	CUE.cpp \
 	VISO.cpp \
 	VCICache.cpp

 if defined(VBOX_WITH_PLUGIN_CRYPT)
  StorageLib_DEFS    += VBOX_WITH_PLUGIN_CRYPT
  StorageLib_SOURCES += \
  	VDFilterCrypt.cpp \
  	VDKeyStore.cpp
 endif
endif # !VBOX_ONLY_EXTPACKS

#StorageLibNoDB_TEMPLATE = VBoxR3Dll
#StorageLibNoDB_DEFS     = IN_VBOXDDU VBOX_HDD_NO_DYNAMIC_BACKENDS
#StorageLibNoDB_SOURCES  = \
#	$(StorageLib_SOURCES)

# generate rules
include $(FILE_KBUILD_SUB_FOOTER)

